AWSTemplateFormatVersion: '2010-09-09'
Description: "flows mintos"
Resources:
  newtransactionFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: newtransaction
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  gettransactionsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: gettransactions
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  getinvestmentsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: getinvestments
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  newtransactionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: newtransactionFunction
      RetentionInDays: 7
  gettransactionsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: gettransactionsFunction
      RetentionInDays: 7
  getinvestmentsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: getinvestmentsFunction
      RetentionInDays: 7
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 321232316075
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
              - Fn::GetAtt: [ newtransactionFunction , Arn ]
              - Fn::GetAtt: [ getinvestmentsFunction , Arn ]
              - Fn::GetAtt: [ gettransactionsFunction , Arn ]
Outputs:
  newtransactionFunction:
    Description: 'newtransaction'
    Value:
      Fn::GetAtt: [ newtransactionFunction , Arn ]
  newtransactionRole:
    Description: 'newtransaction'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  gettransactionsFunction:
    Description: 'gettransactions'
    Value:
      Fn::GetAtt: [ gettransactionsFunction , Arn ]
  gettransactionsRole:
    Description: 'gettransactions'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  getinvestmentsFunction:
    Description: 'getinvestments'
    Value:
      Fn::GetAtt: [ getinvestmentsFunction , Arn ]
  getinvestmentsRole:
    Description: 'getinvestments'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
